---
- name: Determine downlod URL for Ubuntu
  set_fact:
    aws_cloudwatch_agent_download_url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

- name: Determine user
  set_fact:
    aws_cloudwatch_agent_username: ubuntu
  when: not aws_cloudwatch_agent_username

- name: Set full path of downloaded file
  set_fact:
    downloaded_file: "{{ aws_cloudwatch_agent_download_directory }}/amazon-cloudwatch-agent.deb"
